# action.yml
name: 'Godot Headless Build'
description: 'Use prebuilt docker images to quickly export projects for multiple platforms using the Godot Engine'
branding:
  icon: 'package'
  color: 'blue'
inputs:
  preset:
    description: 'name of the export preset'
    required: true
  export_path:
    description: 'export path for the executable'
    required: true

  project_directory:
    description: 'Directory of the project if not the root'
    required: false
  projectfile_directory:
    description: 'Directory containing the project.godot file if not the project_dir'
    required: false
runs:
  using: docker
  image: docker://robpc/godot-export-action:4.1.3
  args:
   - ${{ inputs.preset }}
   - ${{ inputs.export_path }}
   - ${{ inputs.project_directory }}
   - ${{ inputs.projectfile_directory }}