# action.yml
name: 'Godot Headless Build'
description: 'Quickly build from the headless version of the Godot Engine for multiple platforms'
branding:
  icon: 'package'
  color: 'blue'
inputs:
  preset:
    description: 'name of the export preset'
    required: true
  export_path:
    description: 'export path for the executable'
    required: true

  project_directory:
    description: 'Directory of the project if not the root'
    required: false
  projectfile_directory:
    description: 'Directory containing the project.godot file if not the project_dir'
    required: false
runs:
  using: docker
  image: Dockerfile
  # image: docker://robpc/godot-export-action:3.2.3
  args:
   - ${{ inputs.preset }}
   - ${{ inputs.export_path }}
   - ${{ inputs.project_directory }}
   - ${{ inputs.projectfile_directory }}